# Generated by Django 4.0 on 2021-12-14 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='respuestas',
        ),
        migrations.AddField(
            model_name='nivel',
            name='resuelto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='categoriaNivel',
            field=models.ForeignKey(default='6', on_delete=django.db.models.deletion.CASCADE, to='server_rest.categorianivel'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='categoriaNivel',
            field=models.ForeignKey(default='6', on_delete=django.db.models.deletion.CASCADE, to='server_rest.categorianivel'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='esCorrecta',
            field=models.BooleanField(default=False),
        ),
    ]
