# Generated by Django 4.0 on 2021-12-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_rest', '0002_remove_nivel_respuestas_nivel_resuelto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='respuestas',
            field=models.ManyToManyField(to='server_rest.Respuesta'),
        ),
    ]
