# Generated by Django 4.0 on 2021-12-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_rest', '0003_nivel_respuestas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='respuestas',
            field=models.ManyToManyField(related_name='respuestas', to='server_rest.Respuesta'),
        ),
    ]
