# Generated by Django 4.0 on 2021-12-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_rest', '0004_alter_nivel_respuestas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='respuestas',
        ),
        migrations.AddField(
            model_name='nivel',
            name='respuesta',
            field=models.ManyToManyField(to='server_rest.Respuesta'),
        ),
    ]
