# Generated by Django 4.0 on 2021-12-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_rest', '0005_remove_nivel_respuestas_nivel_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='respuesta',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='categoriaNivel',
        ),
        migrations.AddField(
            model_name='nivel',
            name='respuestas',
            field=models.ManyToManyField(related_name='respuestas', to='server_rest.Respuesta'),
        ),
    ]
