# Generated by Django 4.0 on 2021-12-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_rest', '0006_remove_nivel_respuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='respuestas',
            field=models.ManyToManyField(to='server_rest.Respuesta'),
        ),
    ]
